# Generated by Django 4.2.4 on 2023-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('link', models.URLField(max_length=256)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('keep', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
